export const theme = {
  colors: {
    white: '#ffffff',
    background: '#f0f2f3',
    none: 'transparent',
    gray: '#4b4b4d',
    lightGray: '#9d9e9f',
    orange: '#b26423',
    brown: '#99501d',
    primary: '#c8cbab',
    light: '#5b7052',
    gold: 'gold',
    success: '#07bc0c',
    error: '#e74c3c',
    text: 'black',
    blue: '#4649FF',
    green: '#14C38E',
  },
  spacing: {
    xxs: 2,
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
  },
  radius: {
    xs: 2,
    s: 4,
    m: 10,
    l: 16,
  },
  font: {
    size: {
      xs: 8,
      s: 12,
      m: 16,
      l: 20,
      xl: 24,
    },
    family: {
      Gilroy: 'Gilroy-Medium',
      GilroySemiBold: 'Gilroy-SemiBold',
      GilroyBold: 'Gilroy-Bold',
    },
  },
};
